export default [
  { name: 'distance_km', label: 'fields.delivery.distance_km', type: 'number', step: 0.1, defaultValue: 420 },
  { name: 'vehicle_type', label: 'fields.delivery.vehicle_type', type: 'select', options: ['Truck', 'Van', 'Tractor + Trailer', 'Rigid Truck'], defaultValue: 'Tractor + Trailer' },
  { name: 'total_weight_kg', label: 'fields.delivery.total_weight_kg', type: 'number', step: 0.1, defaultValue: 1250 },
  { name: 'total_volume_m3', label: 'fields.delivery.total_volume_m3', type: 'number', step: 0.1, defaultValue: 8.5 },
  { name: 'region', label: 'fields.delivery.region', type: 'text', defaultValue: 'Paris' },
  { name: 'driver_code', label: 'fields.delivery.driver_code', type: 'text', defaultValue: 'DRV-FR-001' },
  { name: 'experience_years', label: 'fields.delivery.experience_years', type: 'number', step: 1, defaultValue: 8 },
  { name: 'day_name', label: 'fields.delivery.day_name', type: 'select', options: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'], defaultValue: 'Friday' },
  { name: 'month_num', label: 'fields.delivery.month_num', type: 'number', step: 1, min: 1, max: 12, defaultValue: 7 },
  { name: 'is_weekend', label: 'fields.delivery.is_weekend', type: 'select', options: [{ value: '0', label: 'fields.options.no' }, { value: '1', label: 'fields.options.yes' }], defaultValue: '0' },
  { name: 'client_type', label: 'fields.delivery.client_type', type: 'select', options: ['B2B', 'B2C'], defaultValue: 'B2B' },
  { name: 'priority_level', label: 'fields.delivery.priority_level', type: 'select', options: ['Low', 'Medium', 'High', 'Critical'], defaultValue: 'Critical' },
  { name: 'difficulty_level', label: 'fields.delivery.difficulty_level', type: 'select', options: ['Low', 'Medium', 'High'], defaultValue: 'Medium' },
  { name: 'zone_type', label: 'fields.delivery.zone_type', type: 'select', options: ['Domestic', 'Cross-border'], defaultValue: 'Domestic' },
  { name: 'planned_time_hours', label: 'fields.delivery.planned_time_hours', type: 'number', step: 0.1, defaultValue: 5.4 },
];
